import { describe, expect, it } from 'vitest';
import { samplePoisson } from '../src/engine/matchSimulator.js';
import { fitPoissonLog, poissonLogLikelihood } from '../src/fitting/poissonGlm.js';
import { testRng } from './testRng.js';

describe('fitPoissonLog', () => {
  it('recovers known coefficients from data generated by the model', () => {
    const rng = testRng(7);
    const trueBeta = [0.45, 0.8, -0.3];

    const x: number[][] = [];
    const y: number[] = [];
    for (let i = 0; i < 20_000; i++) {
      // Spread the predictors over a realistic range rather than clustering at zero.
      const x1 = rng.random() * 2 - 1;
      const x2 = rng.random() * 2 - 1;
      const eta = trueBeta[0]! + trueBeta[1]! * x1 + trueBeta[2]! * x2;
      x.push([1, x1, x2]);
      y.push(samplePoisson(Math.exp(eta), rng));
    }

    const fit = fitPoissonLog(x, y);

    expect(fit.converged).toBe(true);
    for (let j = 0; j < trueBeta.length; j++) {
      // Within four standard errors of truth is a very loose bar that still catches real bugs.
      expect(Math.abs(fit.beta[j]! - trueBeta[j]!)).toBeLessThan(4 * fit.standardErrors[j]!);
      expect(fit.beta[j]!).toBeCloseTo(trueBeta[j]!, 1);
    }
  });

  it('fits an intercept-only model to the log of the sample mean', () => {
    const y = [0, 1, 2, 3, 4, 2, 1, 3, 2, 2];
    const mean = y.reduce((sum, value) => sum + value, 0) / y.length;

    const fit = fitPoissonLog(
      y.map(() => [1]),
      y,
    );

    expect(fit.converged).toBe(true);
    expect(Math.exp(fit.beta[0]!)).toBeCloseTo(mean, 8);
  });

  it('reaches a higher likelihood than any nearby coefficient vector', () => {
    const x = [
      [1, -1],
      [1, -0.5],
      [1, 0],
      [1, 0.5],
      [1, 1],
      [1, 1.5],
    ];
    const y = [1, 1, 2, 3, 4, 6];

    const fit = fitPoissonLog(x, y);

    for (const nudge of [
      [0.05, 0],
      [-0.05, 0],
      [0, 0.05],
      [0, -0.05],
    ]) {
      const perturbed = fit.beta.map((value, j) => value + nudge[j]!);
      expect(poissonLogLikelihood(x, y, perturbed)).toBeLessThan(fit.logLikelihood);
    }
  });

  it('rejects a design matrix whose row count does not match the responses', () => {
    expect(() => fitPoissonLog([[1], [1]], [1])).toThrow(/2 rows but 1 responses/);
  });
});
